pipeline {
  options {
    timeout(time: 60, unit: 'MINUTES')
  }

  environment {
    IMAGE_NAME = 'static-ws'
    IMAGE_REL = 'v1r0'
    CONTAINER_NAME = 'container-static-ws'
    TEST_LOCAL_PORT = 8081
  }
  
  triggers {
    cron('0 1 * * 1-5')
  }

  agent { node { label 'master' } }
  
  stages {
    stage('Step 1') {
      echo "Step 1"
      git branch: "master",
        credentialsId: '917fd0bc-d7df-47c7-922c-55fc235bc0d9',
        url: 'https://github.com/YohannCstd/cicd-static-website.git'
    }
  }
}

